### ISSUE TITLE
Where are the webtree logs

### ISSUE THREAD

**Issue by shreyasajj** [NathanVaughn/webtrees-docker#105]
Im trying to find why it says 500 in the logs for apache and I cant find where the logs are in the server container

**Comment by NathanVaughn** [comment]
The Apache logs are in the defualt location for Ubuntu, which is `/var/log/apache2/`

![image](https://user-images.githubusercontent.com/8636459/190511578-0f82c594-15d7-4dc9-9e5e-72770675846e.png)

**Comment by shreyasajj** [comment]
I was looking for webtree logs if possible

**Comment by NathanVaughn** [comment]
I'm not aware of any logs on disk. I think webtrees just logs messages to the `wt_log` table in SQL.
