### ISSUE TITLE
Automatic log out

### ISSUE THREAD

**Issue by timaschew** [NathanVaughn/webtrees-docker#106]
Sometimes I'm logged out automatically.
In the middle of my work with max timeouts (no interactions on the website) of 1-2 minutes I try to click on a button or a link and then I'm redirected to the login page, because I'm not logged in anymore.

I've tried to check for a timeout value but I have only found in the rersponse headers this entry:

```
date | Sun, 16 Oct 2022 09:52:07 GMT
strict-transport-security | max-age=15724800; includeSubdomains
```

**Comment by NathanVaughn** [comment]
I have not run into this before, I think this would likely be a webtrees issue, and not something related to the Docker container

**Comment by NathanVaughn** [comment]
This may be related to #112
