### ISSUE TITLE
Can't start container

### ISSUE THREAD

**Issue by koroleves** [NathanVaughn/webtrees-docker#113]
`> [NV_INIT] PRETTY_URLS found in environment variables
> [NV_INIT] HTTPS found in environment variables
> [NV_INIT] HTTPS_REDIRECT found in environment variables
> [NV_INIT] SSL_CERT_FILE NOT found in environment variables, using default: /certs/webtrees.crt
> [NV_INIT] SSL_CERT_KEY_FILE NOT found in environment variables, using default: /certs/webtrees.key
> [NV_INIT] BASE_URL found in environment variables
> [NV_INIT] LANG found in environment variables
> [NV_INIT] DB_TYPE found in environment variables
> [NV_INIT] DB_HOST found in environment variables
> [NV_INIT] DB_PORT found in environment variables
> [NV_INIT] DB_USER found in environment variables
> [NV_INIT] DB_PASS found in environment variables
> [NV_INIT] DB_NAME found in environment variables
> [NV_INIT] DB_PREFIX found in environment variables
> [NV_INIT] WT_USER found in environment variables
> [NV_INIT] WT_NAME found in environment variables
> [NV_INIT] WT_PASS found in environment variables
> [NV_INIT] WT_EMAIL found in environment variables
> [NV_INIT] DB_KEY NOT found in environment variables, using default: None
> [NV_INIT] DB_CERT NOT found in environment variables, using default: None
> [NV_INIT] DB_CA NOT found in environment variables, using default: None
> [NV_INIT] DB_VERIFY NOT found in environment variables, using default: None
> [NV_INIT] PHP_MEMORY_LIMIT NOT found in environment variables, using default: 1024M
> [NV_INIT] PHP_MAX_EXECUTION_TIME NOT found in environment variables, using default: 90
> [NV_INIT] PHP_POST_MAX_SIZE NOT found in environment variables, using default: 50M
> [NV_INIT] PHP_UPLOAD_MAX_FILE_SIZE NOT found in environment variables, using default: 50M
> [NV_INIT] Setting up folder permissions for uploads
> [NV_INIT] Updating php.ini
> [NV_INIT] Setting value for memory_limit in php.ini
> [NV_INIT] Setting value for max_execution_time in php.ini
> [NV_INIT] Setting value for post_max_size in php.ini
> [NV_INIT] Setting value for upload_max_filesize in php.ini
> [NV_INIT] Attempting to automate setup wizard
> [NV_INIT] Automating setup wizard
> [NV_INIT] Starting Apache in background
> [NV_INIT] Disabling site webtrees-redir
> Site webtrees-redir already disabled
> [NV_INIT] Disabling site webtrees-ssl
> Site webtrees-ssl already disabled
> [NV_INIT] Enabling site webtrees
> Site webtrees already enabled
> [NV_INIT] Sending setup wizard request
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/urllib/request.py", line 1346, in do_open
>     h.request(req.get_method(), req.selector, req.data, headers,
>   File "/usr/lib/python3.9/http/client.py", line 1255, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
>     self.send(msg)
>   File "/usr/lib/python3.9/http/client.py", line 950, in send
>     self.connect()
>   File "/usr/lib/python3.9/http/client.py", line 921, in connect
>     self.sock = self._create_connection(
>   File "/usr/lib/python3.9/socket.py", line 843, in create_connection
>     raise err
>   File "/usr/lib/python3.9/socket.py", line 831, in create_connection
>     sock.connect(sa)
> ConnectionRefusedError: [Errno 111] Connection refused
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "/docker-entrypoint.py", line 520, in <module>
>     main()
>   File "/docker-entrypoint.py", line 505, in main
>     setup_wizard()
>   File "/docker-entrypoint.py", line 399, in setup_wizard
>     resp = request.urlopen(
>   File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
>     return opener.open(url, data, timeout)
>   File "/usr/lib/python3.9/urllib/request.py", line 517, in open
>     response = self._open(req, data)
>   File "/usr/lib/python3.9/urllib/request.py", line 534, in _open
>     result = self._call_chain(self.handle_open, protocol, protocol +
>   File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python3.9/urllib/request.py", line 1375, in http_open
>     return self.do_open(http.client.HTTPConnection, req)
>   File "/usr/lib/python3.9/urllib/request.py", line 1349, in do_open
>     raise URLError(err)
> urllib.error.URLError: <urlopen error [Errno 111] Connection refused>`

**Comment by koroleves** [comment]
Managed to start container only with sqlite settings sqlite (sorry for my english)

**Comment by NathanVaughn** [comment]
Could you post the environment variables you're using (with redactions)? It looks like the start-up script is trying to run the setup wizard, but for some reason, the connection is getting refused.

You can also try starting the container with no environment variables set, and running the setup wizard manually.

**Comment by koroleves** [comment]
With the old settings, the container worked well until the first reload.
I recreated the container with these settings
version: "3"

services:
   app:
     environment:
       PRETTY_URLS: "1"
       HTTPS: "0"
       HTTPS_REDIRECT: "0"
       LANGUAGE: "ru-RU"
       BASE_URL: "http://wtree.koroles.com"
       DB_TYPE: "mysql"
       DB_NAME: "webtrees"
       DB_HOST: "192.168.1.10"
       DB_PORT: "3306"
       DB_USER: "webtrees"
       DB_PASS: "k3FwgCfg"
       DB_PREFIX: ""
       WT_USER: "admin"
       WT_NAME: "admin"
       WT_PASS: "****"
       WT_EMAIL: "koroleves@ya.ru"
     container_name: webtrees
     image: ghcr.io/nathanvaughn/webtrees:2.1.12
     ports:
       - 3663:80

Now when you restart the container starts but not correctly.

![2022-12-23_12-01-57 (2)](https://user-images.githubusercontent.com/2029394/209306192-eaddbd12-e417-491a-9b6c-85274f64e057.png)

Infinite loading animation

**Comment by koroleves** [comment]
And I can't get log out
![2022-12-23_12-08-25](https://user-images.githubusercontent.com/2029394/209307160-fbd66abb-b540-4a12-abc8-b7d97e95d7e9.png)

**Comment by koroleves** [comment]
the same with these settings, the container worked well until the first reload.

version: "3"

services:
app:
environment:
PRETTY_URLS: "1"
HTTPS: "0"
HTTPS_REDIRECT: "0"
LANGUAGE: "ru-RU"
BASE_URL: "http://wtree.koroles.com/"

container_name: webtrees
image: ghcr.io/nathanvaughn/webtrees:2.1.12
ports:
- 3663:80

after reboot i see endless loading animation

**Comment by NathanVaughn** [comment]
First off, I would try clearing your database and starting fresh.

Second, I think the issue is that `ru-RU` is not a valid locale code. I finally found the list of allowed values here: https://github.com/fisharebest/webtrees/tree/main/resources/lang
