### ISSUE TITLE
Run as a different user

### ISSUE THREAD

**Issue by esamson** [NathanVaughn/webtrees-docker#114]
Is it possible to run as a different user?

One example where I've seen it done is in the [paperless-ngx docker-entrypoint.sh](https://github.com/paperless-ngx/paperless-ngx/blob/8da3ae2c539266d96c8885964f07bf34c69d73c4/docker/docker-entrypoint.sh#L36-L47).

**Comment by NathanVaughn** [comment]
Currently no. I'd have to do some for research in how to accomplish this, I'm not very familiar with running Docker containers as anything other than the root user.

**Comment by haklc** [comment]
I agree, supplying user and group id would be a nice security feature.

**Comment by NathanVaughn** [comment]
Thanks for reminding me about this. I dug through a bunch of linux server.io code and I think should be implemented in latest tag now. please let me know if it works for you
