### ISSUE TITLE
Issues with 2.1.16 (500 internal error)

### ISSUE THREAD

**Issue by jsmith432** [NathanVaughn/webtrees-docker#117]
2.1.16 is broken to me; reporting status 500 with the message below. I had to revert to 2.1.15

`ParseError: syntax error, unexpected token "return", expecting "function" or "const" in /var/www/webtrees/app/Services/UpgradeService.php:342 Stack trace: #0 /var/www/webtrees/vendor/composer/ClassLoader.php(443): Composer\Autoload\ClassLoader::Composer\Autoload\{closure}('/var/www/webtre...') #1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Fisharebest\\Web...') #2 /var/www/webtrees/vendor/illuminate/container/Container.php(877): ReflectionClass->__construct('Fisharebest\\Web...') #3 /var/www/webtrees/vendor/illuminate/container/Container.php(758): Illuminate\Container\Container->build('Fisharebest\\Web...') #4 /var/www/webtrees/vendor/illuminate/container/Container.php(694): Illuminate\Container\Container->resolve('Fisharebest\\Web...', Array) #5 /var/www/webtrees/vendor/illuminate/container/Container.php(1027): Illuminate\Container\Container->make('Fisharebest\\Web...') #6 /var/www/webtrees/vendor/illuminate/container/Container.php(947): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter)) #7 /var/www/webtrees/vendor/illuminate/container/Container.php(908): Illuminate\Container\Container->resolveDependencies(Array) #8 /var/www/webtrees/vendor/illuminate/container/Container.php(758): Illuminate\Container\Container->build('Fisharebest\\Web...') #9 /var/www/webtrees/vendor/illuminate/container/Container.php(694): Illuminate\Container\Container->resolve('Fisharebest\\Web...', Array) #10 /var/www/webtrees/app/Webtrees.php(312): Illuminate\Container\Container->make('Fisharebest\\Web...') #11 /var/www/webtrees/app/Helpers/functions.php(43): Fisharebest\Webtrees\Webtrees::make('Fisharebest\\Web...') #12 /var/www/webtrees/app/Services/ModuleService.php(662): app('Fisharebest\\Web...') #13 [internal function]: Fisharebest\Webtrees\Services\ModuleService::Fisharebest\Webtrees\Services\{closure}('Fisharebest\\Web...', 'check-for-new-v...') #14 /var/www/webtrees/vendor/illuminate/collections/Collection.php(695): array_map(Object(Closure), Array, Array) #15 /var/www/webtrees/app/Services/ModuleService.php(668): Illuminate\Support\Collection->map(Object(Closure)) #16 /var/www/webtrees/app/Services/ModuleService.php(616): Fisharebest\Webtrees\Services\ModuleService->coreModules() #17 /var/www/webtrees/app/Cache.php(60): Fisharebest\Webtrees\Services\ModuleService->Fisharebest\Webtrees\Services\{closure}() #18 /var/www/webtrees/vendor/symfony/cache/Adapter/ArrayAdapter.php(84): Fisharebest\Webtrees\Cache::Fisharebest\Webtrees\{closure}(Object(Symfony\Component\Cache\CacheItem), true) #19 /var/www/webtrees/app/Cache.php(61): Symfony\Component\Cache\Adapter\ArrayAdapter->get('372b64b23390f9d...', Object(Closure)) #20 /var/www/webtrees/app/Services/ModuleService.php(650): Fisharebest\Webtrees\Cache->remember('all-modules', Object(Closure)) #21 /var/www/webtrees/app/Services/ModuleService.php(573): Fisharebest\Webtrees\Services\ModuleService->all(true) #22 /var/www/webtrees/app/Http/Middleware/UseLanguage.php(84): Fisharebest\Webtrees\Services\ModuleService->findByInterface('Fisharebest\\Web...', true) #23 /var/www/webtrees/app/Http/Middleware/UseLanguage.php(63): Fisharebest\Webtrees\Http\Middleware\UseLanguage->languages(Object(Nyholm\Psr7\ServerRequest)) #24 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #25 /var/www/webtrees/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #26 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #27 /var/www/webtrees/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #28 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #29 /var/www/webtrees/app/Http/Middleware/UseDatabase.php(122): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #30 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #31 /var/www/webtrees/app/Http/Middleware/BadBotBlocker.php(282): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #32 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #33 /var/www/webtrees/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #34 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #35 /var/www/webtrees/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #36 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #37 /var/www/webtrees/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #38 /var/www/webtrees/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #39 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #40 /var/www/webtrees/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #41 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #42 /var/www/webtrees/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #43 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #44 /var/www/webtrees/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #45 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #46 /var/www/webtrees/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #47 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #48 /var/www/webtrees/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #49 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #50 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #51 /var/www/webtrees/app/Webtrees.php(275): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest)) #52 /var/www/webtrees/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch(Object(Nyholm\Psr7\ServerRequest), Array) #53 /var/www/webtrees/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest() #54 {main}`

**Comment by NathanVaughn** [comment]
Thanks for pointing this out. It looks the horrible hack I use to keep Webtrees from upgrading itself inside the Docker container has broken. I'll take a look tonight and try to get a fix out.

**Comment by tobbaz** [comment]
I can confirm this issue too on 2.1.16, although 2.15 is working fine for me.

**Comment by NathanVaughn** [comment]
> I can confirm this issue too on 2.1.16, although 2.15 is working fine for me.

I just did a quick as well, and 2.1.15 works fine for me too, and I can replicate the problem with 2.1.16.

**Comment by NathanVaughn** [comment]
Tags `:latest` and `:2.1.17` have been re-pushed to `ghcr.io` and `docker.io`.
Try it, and let me know if it works now.

**Comment by vytux-com** [comment]
Looks good to me now

**Comment by NathanVaughn** [comment]
Fantastic, I'll close this then
