### ISSUE TITLE
PHP exif dependency

### ISSUE THREAD

**Issue by hubbarmatthew** [NathanVaughn/webtrees-docker#13]
Hi, thanks for keeping this up to date.

The latest update is giving me 500 errors on my thumbnails. I think it's related to the new exif rotation detection in 2.0.3 which needs the exif PHP package. Refer below.

https://webtrees.github.io/blog/2020/03/17/new-webtrees-release-2-0-3.html

Thanks.

**Comment by NathanVaughn** [comment]
Thanks for this. Due to the whole Coronavirus and Spring Break, I hadn't actually verified the latest version works after my script auto-updated the image. I'll try to get a fix out in the next day or two. For now, target version `2.0.2`.

**Comment by NathanVaughn** [comment]
It should be fixed now. I pushed a new version to Docker Hub: https://hub.docker.com/r/nathanvaughn/webtrees/builds
