### ISSUE TITLE
Delay required after Apache is launched

### ISSUE THREAD

**Issue by CiViC321** [NathanVaughn/webtrees-docker#130]
The container launch may fail sometime.  If a delay is added after Apache is launched it will always start.

**Comment by NathanVaughn** [comment]
Could you be more specific? Are you referring to the setup wizard? Or do you mean at the end when `apache2-foreground` is launched?

**Comment by CiViC321** [comment]
Hi Nathan

When a server start with many docker containers running, there might not
yet a contect switch between line 383 in docker-entrypoint.py and line
410.  In other words Apache has not yet start completely and then line 408
fails. I did the laxy think and just added a delay before line 410.
Something more elegant might be required :-) but it works.

Thanks for looking to it.

Kind regards
Petri

**Comment by NathanVaughn** [comment]
Thanks for the clarification, I just added a retry system to the setup wizard call. The Action to rebuild the image should be done in about an hour (https://github.com/NathanVaughn/webtrees-docker/actions/runs/6828710311), try it and let me know if that helps. It has an increasing backoff that tries up to 10 times, with an additional second between each try.
