### ISSUE TITLE
Media mount location changed from previous versions

### ISSUE THREAD

**Issue by haklc** [NathanVaughn/webtrees-docker#131]
Hi, it seems that media location has changed from `/var/www/webtrees/media/` to `/var/www/webtrees/data/media/` in a recent release.

**Comment by NathanVaughn** [comment]
Oops, thanks for pointing that out. I will review and fix it tonight, thanks for the PR

**Comment by NathanVaughn** [comment]
Should be fixed in re-pushed tag. Updated the readme and volume mounts
