### ISSUE TITLE
Find duplicates not working

### ISSUE THREAD

**Issue by Pooh063** [NathanVaughn/webtrees-docker#137]
Find duplicates not working
[log.txt](https://github.com/NathanVaughn/webtrees-docker/files/13848147/log.txt)
![Screenshot_1](https://github.com/NathanVaughn/webtrees-docker/assets/17175474/11126c75-36a5-4f67-91b8-6a092d3a5758)
![Screenshot_2](https://github.com/NathanVaughn/webtrees-docker/assets/17175474/254f8def-2f0e-4fc0-a9a3-4d2b6fd31874)
[docker-compose.yml.txt](https://github.com/NathanVaughn/webtrees-docker/files/13848154/docker-compose.yml.txt)

**Comment by sharmay** [comment]
Probably ran into this https://github.com/fisharebest/webtrees/issues/4683

**Comment by Pooh063** [comment]
как это исправить?

**Comment by NathanVaughn** [comment]
Sorry, I was on a trip. I don't have this issue on my instance, and I don't think this is a result of being containerized. This may be due to some plugins you have installed.

**Comment by Pooh063** [comment]
Вернусь к вопросу...

**Comment by NathanVaughn** [comment]
Do you have a .gedcom file or something to replicate this with? I haven't been able to replicate this and it's likely an upstream issue.

**Comment by Pooh063** [comment]
Этот эффект возникает при использовании базы данных SQLite
С MariaDB проблем и ошибок нет

**Comment by NathanVaughn** [comment]
Ah, `sqlite` was the missing piece. This looks like it's the same as https://github.com/fisharebest/webtrees/issues/3794.
This is an issue with upstream Webtrees, not the Docker container.
I highly recommend using MariaDB or MySQL, those have the best support.
