### ISSUE TITLE
How to enable maps in webtrees?

### ISSUE THREAD

**Issue by koroleves** [NathanVaughn/webtrees-docker#138]
I can't customize the maps. [This service requires an API key. ] Requires an API, but there is no field to enter it.

**Comment by NathanVaughn** [comment]
Once you enable a map provider, click the wrench, and that will take you to a screen to enter an API key.
![image](https://github.com/NathanVaughn/webtrees-docker/assets/8636459/2c533028-7a66-41cd-b54d-4f6286548329)
![image](https://github.com/NathanVaughn/webtrees-docker/assets/8636459/2007e3eb-8d02-483d-a04b-2c01dd18f89e)

**Comment by koroleves** [comment]
Thank you very much for such an comprehensive answer. Google maps provides paid services. How can I use openstreetmap? There are no settings for this mapping service.

**Comment by koroleves** [comment]
> 

> Once you enable a map provider, click the wrench, and that will take you to a screen to enter an API key. ![image](https://private-user-images.githubusercontent.com/8636459/309924481-2c533028-7a66-41cd-b54d-4f6286548329.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjYwMzEsIm5iZiI6MTcwOTYyNTczMSwicGF0aCI6Ii84NjM2NDU5LzMwOTkyNDQ4MS0yYzUzMzAyOC03YTY2LTQxY2QtYjU0ZC00ZjYyODY1NDgzMjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMDgwMjExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTIxZDg1YTljZDcwZjVjNmI4ZTgyZWFjNjFlN2I1ZDRlMDdlZTAxMTIyMzM3MTA3YTRiM2U0ZDIxNDRkYjMzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mUtuhBURWJfFTGexzIFmLhfVpo7JtqXs0fcvs9Hf6v8) ![image](https://private-user-images.githubusercontent.com/8636459/309924501-2007e3eb-8d02-483d-a04b-2c01dd18f89e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjYwMzEsIm5iZiI6MTcwOTYyNTczMSwicGF0aCI6Ii84NjM2NDU5LzMwOTkyNDUwMS0yMDA3ZTNlYi04ZDAyLTQ4M2QtYTA0Yi0yYzAxZGQxOGY4OWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDVUMDgwMjExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmYwY2RhYjJmYTM3YzQ2Yjk1ZTExMGNjODgyZTE5ZTZmMzdhZGJjNDBhYzg5NDNjZjY4NDZiMDMzM2MxMGUwYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jPyaMgqvdm1lGP_HNOhSV2xvF-Pj7nzvr57p1G3nkOk)

Thank you very much for such an comprehensive answer. Google maps provides paid services. How can I use openstreetmap? There are no settings for this mapping service.

**Comment by NathanVaughn** [comment]
openstreetmaps is free, so you just need to enable it. Beyond that, refer to the webtrees documentation: https://webtrees.net/faq/locations/
I don't maintain webtrees, just the Docker container
