### ISSUE TITLE
Latest/2.1.20 only available for linux/arm64

### ISSUE THREAD

**Issue by IDmedia** [NathanVaughn/webtrees-docker#144]
The latest version is only built for linux/arm64 resulting in docker pull failing from a normal linux/amd64 machine.
Source (but affects the other souces too): https://hub.docker.com/r/nathanvaughn/webtrees/tags

**Comment by NathanVaughn** [comment]
Dang it. I reorganized the GitHub Actions to build the different
architectures in parallel, but I guess this somehow broke how this gets
pushed to the registries. I'll take a look tonight

**Comment by NathanVaughn** [comment]
Related docker/build-push-action#671

**Comment by NathanVaughn** [comment]
Should be fixed now, going to try and figure out parallel platform builds and not break prod this time 🙃https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners

**Comment by NathanVaughn** [comment]
Fixed, sorry. See #178
