### ISSUE TITLE
How run again first run?

### ISSUE THREAD

**Issue by dragonerix** [NathanVaughn/webtrees-docker#146]
I had a SQLite database and I needed to switch it to Mariadb. Unfortunately, it wants to log in and the account originally created doesn't work. How do I recreate the first and main administrator? I have a backup of the family tree from the original database. I've already tried uninstalling and deleting everything, but it didn't help. Thank you

**Comment by NathanVaughn** [comment]
Sorry I didn't get to this earlier, I was on vacation. If you want to run the setup wizard from scratch, you need to remove the `/var/www/webtrees/data/config.ini.php` file and wipe the database. I'm afraid I don't know how to change your permissions directly in the database.

Before you nuke everything, I would recommend exporting the GEDCOM file, and then re-importing that after setting up MariaDB.
