### ISSUE TITLE
Backup of database

### ISSUE THREAD

**Issue by KLelong** [NathanVaughn/webtrees-docker#153]
Hi,
Any suggestions how to backup the database ?
The webtrees-website mentions two possibilities : phpMyAdmin and mysqldump.
phpMyAdmin needs to be installed (which it isn't AFAIK) and for mysqldump you need to access the console of one of the containers, which is not possible (again AFAIK).
I'm using portainer if that matters (I'm a container-noob).

Thanks.

**Comment by NathanVaughn** [comment]
For the database container, if you're using the standard MariaDB or MySQL image, `mysqldump` is definitely pre-installed. Attaching a console is easy in Portainer, just click the Console button at the bottom of the container status

![image](https://github.com/user-attachments/assets/79ccfea6-2b75-425a-9b50-1532c3a4a337)

From there, run the `mysqldump` command and save it to a file you can get out of the container.  Example:

```bash
mysqldump webtrees -u webtrees -p > /data/webtrees.sql
```

Personally, I just backup the contents of `/var/lib/mysql` as part of a daily job.

**Comment by KLelong** [comment]
Well, that's my problem. I can't connect to the console.
I click on "console" and I get this : 
![webtrees-db-console](https://github.com/user-attachments/assets/7041443e-8ece-44ee-a61e-bb34533b1d1e)
I then click on "connect" and I get this : 
![webtrees-db-console-login](https://github.com/user-attachments/assets/9653f8f4-93af-4515-bcb3-ff0442408fb7)
forever or until I click on "connecting" which terminates the "connection".
Using root as user does not make a difference.

I do have a regular copy of the whole stack, but I would like to have a copy of the system to install on a shared-web-space provider, so not dockerized.
Besides that, I think copying a running database is not really safe as a backup.

**Comment by KLelong** [comment]
I had to do something with another docker-stack, and there also I can't connect to the console, so it's not the webtrees stack that has a problem, but my docker/portainer installation.

**Comment by NathanVaughn** [comment]
On the host that is running the container, you can also attach a shell manually:

```bash
 docker exec -it 2fe042727364cb21bd200886d4fc671f401589ba80e74d23ddd39dc71401744e /bin/bash
```

Where the hexadecimal string is the container ID.

If you want to schedule a backup job or something, replace `/bin/bash` with the `mysqldump` command you want to run instead.

**Comment by KLelong** [comment]
Forgot to feed back.
I used your last command to backup my database : 
`docker exec -it webtrees-app-1 mysqldump --host=db -u <webtrees db-user> -p<webtrees db-passw> --databases webtrees > webtrees-20241120-2.sql`

Thanks.
