### ISSUE TITLE
Clarify usage of themes folder

### ISSUE THREAD

**Issue by BayerSe** [NathanVaughn/webtrees-docker#43]
Hey Nathan,

thank you very much for your work! I'm currently testing webtrees via your docker image and it looks really solid.

I wanted to install a  [custom theme](https://github.com/JustCarmen/webtrees-theme-justlight) and to do so I unzipped it into the volume that is mounted to `/var/www/webtrees/themes/`. Upon that, nothing happens. After reading the [documentation of webtrees](https://webtrees.net/download/modules) it seems as if themes belong in `modules_v4`. When moving the theme folder into that directory, it appears inside webtrees.

Could you please clarify the intended usage of `- app_themes:/var/www/webtrees/themes/` - did I overlook something?

Thank you
Sebastian

**Comment by BayerSe** [comment]
I just realized that this is probably a relic from v1.7.

**Comment by NathanVaughn** [comment]
Hey Sebastian,

Thanks for the well-written issue. You are completely correct, that's a relic from pre v2.0. I dog-food myself with this image, but totally forgot to update that documentation. I just updated the README on GitHub and on Docker Hub which should cover it better now.
