### ISSUE TITLE
Latest image using PHP 8 causing errors - webtrees 2.0 requires PHP 7.1 -> PHP 7.4

### ISSUE THREAD

**Issue by ThRPctmylSgltwH** [NathanVaughn/webtrees-docker#79]
Current :latest docker image is using PHP 8
You are using webtrees 2.0.x with PHP 8.0
webtrees 2.0 requires PHP 7.1 -> PHP 7.4
Support for PHP 8.0 will come with webtrees 2.1.

see - https://github.com/fisharebest/webtrees/issues/4069#issuecomment-941271149

Am I doing something wrong by pulling the latest image?

**Comment by NathanVaughn** [comment]
Issue fixed for webtrees 2.0.16 and 2.0.17 in all registries. please re-pull the image.
