### ISSUE TITLE
latest tag does not include all images - only amd64

### ISSUE THREAD

**Issue by ThRPctmylSgltwH** [NathanVaughn/webtrees-docker#81]
I have been using the yaml file below for webtrees without issues until the latest change.

I now see the following error when updating the stack.

Failure
failed to deploy a stack: volumes Additional property /srv/dev-disk-by-uuid/Files/AppData/Databases/webtrees is not allowed

The error is on the volumes:

I am using Open Media Vault with Docker 5:20.10.9~3-0~debian-buster and deploying the stack with Portainer 2.9.1. The system is a Raspberry PI 4 with 4 GB RAM.

It has worked perfectly until today when I had to update the stack due to the issue with PHP8 being downgraded to PHP7.4.

Is there a solution?

version: "2.1"
services:
  app:
    depends_on:
      - db
    image: ghcr.io/nathanvaughn/webtrees:latest
    environment:
      PRETTY_URLS: "1"
      LANG: "en-US"
      BASE_URL: "https://webtrees.falcigno.tk"
      DB_TYPE: "mysql"
      DB_HOST: "db"
      DB_PORT: "3306"
      DB_USER: "webtrees"
      DB_PASS: "badpassword"
      DB_NAME: "webtrees"
      DB_PREFIX: "wt_"
      WT_USER: "username"
      WT_NAME: "Full Name"
      WT_PASS: "mybadpassword"
      WT_EMAIL: "me@example.com"
    ports:
      - 8091:80
    links:
      - db
    restart: unless-stopped
    volumes:
      - /srv/dev-disk-by-uuid/Files/AppData/Config/webtrees/data:/var/www/webtrees/data/
      - /srv/dev-disk-by-uuid/Files/AppData/Config/webtrees/media:/var/www/webtrees/media/
      - /srv/dev-disk-by-uuid/Files/AppData/Config/webtrees/themes:/var/www/webtrees/modules_v4/

  db:
    image: yobasystems/alpine-mariadb:10.4.17
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_DATABASE: "webtrees"
      MYSQL_USER: "webtrees"
      MYSQL_ROOT_PASSWORD: "badpassword"
      MYSQL_PASSWORD: "badpassword"
    restart: unless-stopped
    volumes:
      - /srv/dev-disk-by-uuid/Files/AppData/Databases/webtrees:/var/lib/mysql

volumes:
  /srv/dev-disk-by-uuid/Files/AppData/Databases/webtrees:
    driver: local
  /srv/dev-disk-by-uuid/Files/AppData/Config/webtrees/data:
    driver: local
  /srv/dev-disk-by-uuid/Files/AppData/Config/webtrees/media:
    driver: local
  /srv/dev-disk-by-uuid/Files/AppData/Config/webtrees/themes:
    driver: local

**Comment by NathanVaughn** [comment]
I have no idea. I'm running the latest image also from `ghcr.io` on my server with no issue. The only thing that changed in the image was the PHP runtime, otherwise the Dockerfile is the exact same.

![image](https://user-images.githubusercontent.com/8636459/137223898-2ccd5727-672b-4d59-aa84-e23154563435.png)

**Comment by ThRPctmylSgltwH** [comment]
It works perfectly now.
Thank you for keeping this project alive and making it available to the community.
You work is appreciated.
