### ISSUE TITLE
Email not working after webtrees update 2.0.19 > 2.0.21

### ISSUE THREAD

**Issue by rubenixnagios** [NathanVaughn/webtrees-docker#88]
Hello there, first of all thanks so much for this lovely docker image.

Since 2.0.19 update to 2.0.21 email does not work and getting this error message when sending test mail from control panel.
Im using gmail account and SMTP options well configured (Port, user & pass)

the update was just pull latest image and run the docker-compose up -d command 

Here the error:

`Fatal error: Declaration of Egulias\EmailValidator\Validation\MessageIDValidation::isValid(string $email, Egulias\EmailValidator\EmailLexer $emailLexer): bool must be compatible with Egulias\EmailValidator\Validation\EmailValidation::isValid($email, Egulias\EmailValidator\EmailLexer $emailLexer) in /var/www/webtrees/vendor/egulias/email-validator/src/Validation/MessageIDValidation.php on line 23`

Same happened a time ago but can't remember what I did to solve it.

Any idea?

Thanks so much in advance.

System: Raspberry pi 4 running raspbian and webtres in a docker container

**Comment by NathanVaughn** [comment]
I can replicate this too, not sure why is this occurring yet. I'm not much of a PHP person.

**Comment by rubenixnagios** [comment]
no worries, hope someone finds a solution on this

btw found this over webtrees forum 

[https://www.webtrees.net/index.php/en/forum/help-for-2-0/35568-sending-email-is-not-working-in-2-0-14](url)

As have it on Docker don't know how to proceed.

Anyways on 2.0.19 docker container it was working. Maybe I try to downgrade to that version...

thanks, let me know if you fins a solution!

**Comment by rubenixnagios** [comment]
reverted back to 2.0.19 --> I can confirm email is working again.

compared both versions of /var/www/webtrees/vendor directories & are exactly the same! size and files

dunno, I will stay on this version until I find a solution!

will try to compare both /var/www/webtrees versions

**Comment by NathanVaughn** [comment]
From looking at the webtrees forums, it seems this new file added causes the issue: https://www.webtrees.net/index.php/fr/forum/help-for-2-0/36616-email-error-after-update-to-2-0-21#89985 
I can confirm on my Webtrees 2.0.19 container, the file is not there. I'll try to get a patch out today that removes the file in the container.

**Comment by NathanVaughn** [comment]
I have tested it on my machine and that does appear to fix the issue. Just need to re-push the latest tag now.

**Comment by NathanVaughn** [comment]
Issue should be resolved, repull the `:latest` or `:2.0.21` tag.

**Comment by rubenixnagios** [comment]
cool, will try this 2moro
that was fast indeed
