### ISSUE TITLE
Language files missing in image?

### ISSUE THREAD

**Issue by benboit** [NathanVaughn/webtrees-docker#9]
Hey there,

i wanted to test your setup and im not able to access the frontend in the browser. This stack-trace is returned:

Fatal error: Uncaught ErrorException: file(/var/www/webtrees/app/../resources/lang/de/messages.po): failed to open stream: No such file or directory in /var/www/webtrees/vendor/fisharebest/localization/src/Translation.php:56 Stack trace: #0 [internal function]: Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}(2, 'file(/var/www/w...', '/var/www/webtre...', 56, Array) #1 /var/www/webtrees/vendor/fisharebest/localization/src/Translation.php(56): file('/var/www/webtre...') #2 /var/www/webtrees/app/I18N.php(306): Fisharebest\Localization\Translation->__construct('/var/www/webtre...') #3 /var/www/webtrees/app/Http/Controllers/SetupController.php(140): Fisharebest\Webtrees\I18N::init('de', true) #4 /var/www/webtrees/app/Http/Middleware/ReadConfigIni.php(69): Fisharebest\Webtrees\Http\Controllers\SetupController->setup(Object(Nyholm\Psr7\ServerRequest)) #5 /var/www/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerReques in /var/www/webtrees/vendor/fisharebest/localization/src/Translation.php on line 56

A look in the running container shows, that all language files seem to be missing (/var/www/webtrees/resources/lang), allthough the parent folders are in place.

**Comment by NathanVaughn** [comment]
Thanks for the report. This should now be corrected on the latest stable and beta builds:
https://hub.docker.com/layers/nathanvaughn/webtrees/2.0.1/images/sha256-9898b8d9115802c0cd153ba16cc546f520f3a9b1d85bf72c7ef42a6f788f6158
